name: encourage
description: App for EnCourage.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  speech_to_text: ^4.1.0-nullsafety
  image_picker: ^0.7.4
  video_player: ^2.1.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
